// tslint:disable
/**
 * Akrochem ERP API
 * Akrochem API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    ProductCompanyLocation,
} from './';

/**
 * @export
 * @interface Product
 */
export interface Product {
    /**
     * Unique id for the product
     * @type {string}
     * @memberof Product
     */
    id?: string;
    /**
     * @type {string}
     * @memberof Product
     */
    externalSystemId?: string;
    /**
     * @type {string}
     * @memberof Product
     */
    description?: string;
    /**
     * @type {string}
     * @memberof Product
     */
    status?: ProductStatusEnum;
    /**
     * Maps to inventory_class_id
     * @type {string}
     * @memberof Product
     */
    classificationId?: string;
    /**
     * @type {string}
     * @memberof Product
     */
    categoryId?: string;
    /**
     * @type {string}
     * @memberof Product
     */
    shelfLifeId?: string;
    /**
     * @type {string}
     * @memberof Product
     */
    stockUnitId?: string;
    /**
     * @type {string}
     * @memberof Product
     */
    companyNumber?: string;
    /**
     * @type {string}
     * @memberof Product
     */
    companyName?: string;
    /**
     * @type {string}
     * @memberof Product
     */
    companyLocationId?: string;
    /**
     * @type {ProductCompanyLocation}
     * @memberof Product
     */
    companyLocation?: ProductCompanyLocation;
    /**
     * @type {string}
     * @memberof Product
     */
    companyProductNumber?: string;
    /**
     * @type {string}
     * @memberof Product
     */
    companyProductDescription?: string;
    /**
     * @type {boolean}
     * @memberof Product
     */
    isFireHazard?: boolean;
    /**
     * @type {boolean}
     * @memberof Product
     */
    isPressureHazard?: boolean;
    /**
     * @type {boolean}
     * @memberof Product
     */
    isReactivityHazard?: boolean;
    /**
     * @type {boolean}
     * @memberof Product
     */
    isImmediateHazard?: boolean;
    /**
     * @type {boolean}
     * @memberof Product
     */
    isDelayHazard?: boolean;
    /**
     * @type {boolean}
     * @memberof Product
     */
    isMarineHazard?: boolean;
    /**
     * @type {boolean}
     * @memberof Product
     */
    isUsHazard?: boolean;
    /**
     * @type {boolean}
     * @memberof Product
     */
    isInternationalHazard?: boolean;
    /**
     * @type {boolean}
     * @memberof Product
     */
    isConsignment?: boolean;
    /**
     * @type {boolean}
     * @memberof Product
     */
    isNonStock?: boolean;
    /**
     * @type {boolean}
     * @memberof Product
     */
    doesPrintInternalLabels?: boolean;
    /**
     * @type {number}
     * @memberof Product
     */
    specificGravity?: number;
    /**
     * @type {number}
     * @memberof Product
     */
    standardPackageWeight?: number;
    /**
     * @type {string}
     * @memberof Product
     */
    standardPackageUnit?: ProductStandardPackageUnitEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum ProductStatusEnum {
    Active = 'ACTIVE',
    Rejected = 'REJECTED',
    PendingApproval = 'PENDING_APPROVAL',
    Discontinued = 'DISCONTINUED',
    Approved = 'APPROVED'
}
/**
 * @export
 * @enum {string}
 */
export enum ProductStandardPackageUnitEnum {
    Lb = 'LB'
}

