// tslint:disable
/**
 * Akrochem ERP API
 * Akrochem API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface ProductCompanyLocation
 */
export interface ProductCompanyLocation {
    /**
     * @type {string}
     * @memberof ProductCompanyLocation
     */
    id?: string;
    /**
     * @type {string}
     * @memberof ProductCompanyLocation
     */
    companyId?: string;
    /**
     * @type {string}
     * @memberof ProductCompanyLocation
     */
    externalSystemId?: string;
    /**
     * @type {string}
     * @memberof ProductCompanyLocation
     */
    attention?: string | null;
    /**
     * @type {string}
     * @memberof ProductCompanyLocation
     */
    phoneNumber?: string | null;
    /**
     * @type {string}
     * @memberof ProductCompanyLocation
     */
    altPhoneNumber?: string | null;
    /**
     * @type {string}
     * @memberof ProductCompanyLocation
     */
    faxNumber?: string | null;
    /**
     * @type {string}
     * @memberof ProductCompanyLocation
     */
    name?: string;
    /**
     * @type {boolean}
     * @memberof ProductCompanyLocation
     */
    isActive?: boolean;
    /**
     * @type {string}
     * @memberof ProductCompanyLocation
     */
    address1?: string;
    /**
     * @type {string}
     * @memberof ProductCompanyLocation
     */
    address2?: string | null;
    /**
     * @type {string}
     * @memberof ProductCompanyLocation
     */
    city?: string;
    /**
     * @type {string}
     * @memberof ProductCompanyLocation
     */
    regionIsoCode?: string;
    /**
     * @type {string}
     * @memberof ProductCompanyLocation
     */
    postalCode?: string;
    /**
     * @type {string}
     * @memberof ProductCompanyLocation
     */
    countryIsoCode?: string;
    /**
     * @type {string}
     * @memberof ProductCompanyLocation
     */
    notes?: string | null;
}
